[package]
name = "day-four"
version = "0.1.0"
authors = ["isaakyansane"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
itertools = "0.10"
raster = "0.2.0"
